Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2024-07, with the labels that each got.

#414 Lognormal droplets in parcel
  NEWS.md
  docs/src/IceNucleationParcel0D.md
  papers/ice_nucleation_2024/calibration.jl
  papers/ice_nucleation_2024/calibration_setup.jl
  parcel/Example_Deposition_Nucleation.jl
  parcel/Example_Frostenberg_Immersion_Freezing.jl
  parcel/Example_Immersion_Freezing.jl
  parcel/Example_Liquid_only.jl
  parcel/Example_P3_ice_nuc.jl
  parcel/Example_P3_vs_activitybased.jl
  parcel/Example_Tully_et_al_2023.jl
  parcel/ParcelDistributions.jl
  parcel/ParcelModel.jl
  parcel/ParcelTendencies.jl
Labels: Parcel

#417 Pin MLJFlux at version 0.4
  Project.toml
  test/Project.toml
Labels: tests, packages 🍱, Aerosol Activation :bulb:

#418 Try fixing 1M scheme for ClimaAtmos
  src/Microphysics1M.jl
  test/microphysics1M_tests.jl
Labels: tests, Approved :four_leaf_clover:

#415 Implement a modified terminal velocity as an option in SB2006
  NEWS.md
  Project.toml
  docs/bibliography.bib
  docs/src/Microphysics2M.md
  docs/src/plots/TerminalVelocityComparisons.jl
  src/Microphysics2M.jl
  test/gpu_tests.jl
  test/microphysics2M_tests.jl
Labels: Approved :four_leaf_clover:

#419 bump version for a new release
  Project.toml
Labels: packages 🍱

#421 Add diameter distribution functions and bounds
  docs/src/API.md
  docs/src/Microphysics2M.md
  docs/src/plots/RainEvapoartionSB2006.jl
  src/Microphysics2M.jl
  test/microphysics2M_tests.jl
Labels: P3

#423 breakup the P3 scheme file
  src/CloudMicrophysics.jl
  src/P3.jl
  src/P3Scheme.jl
  src/P3_helpers.jl
  src/P3_particle_properties.jl
  src/P3_processes.jl
  src/P3_size_distribution.jl
  src/P3_terminal_velocity.jl
Labels: P3

#425 Add P3 terminal velocity functions
  docs/src/API.md
  docs/src/plots/P3TerminalVelocityPlots.jl
  src/CloudMicrophysics.jl
  src/Microphysics2M.jl
  src/P3.jl
  src/P3_terminal_velocity.jl
  src/TerminalVelocity.jl
  test/p3_tests.jl
  test/performance_tests.jl
  test/runtests.jl
  test/terminal_velocity_tests.jl
Labels: P3

#426 Simplify the P3 terminal velocity
  docs/src/plots/P3TerminalVelocityPlots.jl
  src/P3_size_distribution.jl
  src/P3_terminal_velocity.jl
  test/p3_tests.jl
  test/performance_tests.jl
Labels: P3

#427 Bring back the velocity perf test
  src/P3_particle_properties.jl
  test/performance_tests.jl
Labels: P3

#428 update notation q -> L
  docs/src/P3Scheme.md
  docs/src/plots/P3LambdaErrorPlots.jl
  docs/src/plots/P3SchemePlots.jl
  docs/src/plots/P3ShapeSolverPlots.jl
  docs/src/plots/P3TerminalVelocityPlots.jl
  src/P3_particle_properties.jl
  src/P3_size_distribution.jl
  src/P3_terminal_velocity.jl
  test/p3_tests.jl
Labels: P3
