Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2024-11, with the labels that each got.

#474 Adding AIDA HET artifacts
  Artifacts.toml
  papers/ice_nucleation_2024/AIDA_calibrations.jl
  papers/ice_nucleation_2024/AIDA_data_artifact/OutputArtifacts.toml
Labels: Approved :four_leaf_clover:

#475 Revamp Chen2022 parameterization to allow variable apparent ice/snow density
  docs/src/API.md
  docs/src/plots/P3Melting.jl
  docs/src/plots/TerminalVelocity.jl
  src/Common.jl
  src/Microphysics1M.jl
  src/MicrophysicsNonEq.jl
  src/P3_processes.jl
  src/P3_terminal_velocity.jl
  src/parameters/Microphysics1M.jl
  src/parameters/TerminalVelocity.jl
  test/common_functions_tests.jl
  test/common_types_tests.jl
  test/microphysics1M_tests.jl
  test/microphysics_noneq_tests.jl
  test/p3_tests.jl
Labels: Ice :snowman:

#477 Update 1M scheme to use apparent densities for snow and cloud ice
  src/parameters/Microphysics1M.jl
  test/common_functions_tests.jl
  test/gpu_tests.jl
  test/microphysics1M_tests.jl
  test/microphysics_noneq_tests.jl
Labels: Terminal velocity

#478 its still basically zero
  src/Common.jl
Labels: bikeshedding :bike: :house:

#479 Bump version for new release - 0.22.4
  Project.toml
Labels: packages 🍱

#481 combine box and parcel models
  docs/Project.toml
  parcel/ParcelModel.jl
Labels: Parcel, Approved :four_leaf_clover:

#480 HET J defaults to 0 for any aerosol type
  src/IceNucleation.jl
  test/heterogeneous_ice_nucleation_tests.jl
Labels: Ice :snowman:, Approved :four_leaf_clover:

#483 Fix DocumenterCitations error
  docs/Project.toml
  docs/bibliography.bib
Labels: documentation, packages 🍱, Approved :four_leaf_clover:

#486 Add perf tests for Chen2022 terminal velocity
  test/gpu_tests.jl
  test/performance_tests.jl
Labels: Terminal velocity, ci

#490 Change to using Last, First format in docs
  docs/bibliography.bib
  docs/src/assets/citations.css
Labels: documentation, bikeshedding :bike: :house:

#491 update codecov action
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
Labels: ci, dependencies
