Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2024-10, with the labels that each got.

#462 Add cloud condensate sedimentation velocity
  docs/Project.toml
  docs/bibliography.bib
  docs/make.jl
  docs/src/API.md
  docs/src/Microphysics1M.md
  docs/src/Microphysics2M.md
  docs/src/MicrophysicsNonEq.md
  docs/src/P3Scheme.md
  docs/src/TerminalVelocity.md
  docs/src/plots/Microphysics1M_plots.jl
  docs/src/plots/TerminalVelocity.jl
  docs/src/plots/TerminalVelocity2M.jl
  docs/src/plots/TerminalVelocityComparisons.jl
  src/Common.jl
  src/Microphysics1M.jl
  src/Microphysics2M.jl
  src/MicrophysicsNonEq.jl
  src/P3_helpers.jl
  src/P3_size_distribution.jl
  src/P3_terminal_velocity.jl
  src/parameters/Microphysics1M.jl
  test/common_functions_tests.jl
  test/microphysics1M_tests.jl
  test/microphysics_noneq_tests.jl
Labels: enhancement

#463 Update climacommon to 2024_10_09
  .buildkite/longruns/pipeline.yml
  .buildkite/pipeline.yml
  test/performance_tests.jl
Labels: Approved :four_leaf_clover:

#470 Try manually applying dependabot changes
  .github/workflows/CodeCov.yml
  .github/workflows/DocCleanup.yml
  .github/workflows/JuliaFormatter.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: ci, dependencies

#460 Add UKI to AIDA ice nucleation calibrations
  papers/Project.toml
  papers/ice_nucleation_2024/AIDA_calibrations.jl
  papers/ice_nucleation_2024/calibration.jl
  papers/ice_nucleation_2024/calibration_setup.jl
  papers/ice_nucleation_2024/perfect_calib.jl
  test/Project.toml
  test/aerosol_activation_calibration.jl
  test/ice_nucleation_calibration.jl
Labels: needs review
