Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2024-08, with the labels that each got.

#434 Cleanup in 2M size distributions
  src/Microphysics2M.jl
  test/microphysics2M_tests.jl
Labels: P3, Approved :four_leaf_clover:

#432 Aspect Ratio Capability in P3 Velocities
  docs/src/P3Scheme.md
  docs/src/assets/p3_mascot.png
  docs/src/plots/P3AspectRatioPlot.jl
  docs/src/plots/P3SchemePlots.jl
  docs/src/plots/P3TerminalVelocityPlots.jl
  src/P3_particle_properties.jl
  src/P3_size_distribution.jl
  src/P3_terminal_velocity.jl
  test/p3_tests.jl
  test/performance_tests.jl
Labels: P3, Approved :four_leaf_clover:

#435 Add P3 immersion freezing
  docs/src/API.md
  docs/src/P3Scheme.md
  docs/src/plots/P3ImmersionFreezing.jl
  src/P3_processes.jl
  test/p3_tests.jl
  test/performance_tests.jl
Labels: P3

#429 Aerosol activation in parcel
  NEWS.md
  docs/src/IceNucleationParcel0D.md
  parcel/Example_AerosolActivation.jl
  parcel/ParcelModel.jl
  parcel/ParcelParameters.jl
  parcel/ParcelTendencies.jl
  parcel/Project.toml
Labels: Parcel, Approved :four_leaf_clover:

#439 Add a new nonequilibrium cloud formation
  docs/bibliography.bib
  docs/src/API.md
  docs/src/IceNucleationParcel0D.md
  docs/src/MicrophysicsNonEq.md
  src/MicrophysicsNonEq.jl
  test/gpu_tests.jl
  test/microphysics_noneq_tests.jl
  test/performance_tests.jl
Labels: Ice :snowman:, needs review

#443 Temporary fix for unstable ice bound
  src/P3_size_distribution.jl
  test/p3_tests.jl
  test/performance_tests.jl
Labels: bugfix, P3

#446 Add ice melting rate to P3
  docs/src/API.md
  docs/src/P3Scheme.md
  docs/src/plots/P3Melting.jl
  src/P3_particle_properties.jl
  src/P3_processes.jl
  test/p3_tests.jl
  test/performance_tests.jl
Labels: P3, Approved :four_leaf_clover:

#440 P3 velocities with liquid fraction
  docs/bibliography.bib
  docs/src/P3Scheme.md
  docs/src/plots/Cholette2019_fig1.jl
  docs/src/plots/P3AspectRatioPlot.jl
  docs/src/plots/P3LambdaErrorPlots.jl
  docs/src/plots/P3SchemePlots.jl
  docs/src/plots/P3ShapeSolverPlots.jl
  docs/src/plots/P3TerminalVelocityPlots.jl
  docs/src/plots/P3TerminalVelocityPlots_WithFliq.jl
  docs/src/plots/P3TerminalVelocity_F_liq_rim.jl
  p3_sandbox/p3_sandbox.jl
  src/P3_helpers.jl
  src/P3_particle_properties.jl
  src/P3_processes.jl
  src/P3_size_distribution.jl
  src/P3_terminal_velocity.jl
  test/gpu_tests.jl
  test/p3_tests.jl
  test/performance_tests.jl
Labels: P3, Approved :four_leaf_clover:

#447 Bump version for a new release, delete NEWS.md
  NEWS.md
  Project.toml
Labels: packages 🍱
