Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2024-04, with the labels that each got.

#363 Add EKP calibration of ARG to emulators ext
  Project.toml
  docs/src/AerosolActivation.md
  ext/Common.jl
  ext/EmulatorModelsExt.jl
  test/Project.toml
  test/aerosol_activation_calibration.jl
  test/runtests.jl
Labels: enhancement, Aerosol Activation :bulb:, Approved :four_leaf_clover:

#343 Perfect model calibration of ABDINM & ABIFM
  papers/Project.toml
  papers/ice_nucleation_2024/perfect_model_J.jl
  papers/ice_nucleation_2024/plot_ensemble_mean.jl
  parcel/ParcelTendencies.jl
  test/Project.toml
  test/ice_nucleation_calibration.jl
  test/runtests.jl
Labels: Approved :four_leaf_clover:

#368 radar reflectivity
  docs/src/API.md
  docs/src/Microphysics1M.md
  docs/src/plots/MarshallPalmer_distribution.jl
  src/Microphysics1M.jl
  test/microphysics1M_tests.jl
  test/performance_tests.jl
Labels: enhancement, Approved :four_leaf_clover:

#366 Linear HOM J option
  docs/src/API.md
  docs/src/IceNucleation.md
  docs/src/plots/HomFreezingPlots.jl
  docs/src/plots/linear_HOM_J.jl
  parcel/ParcelTendencies.jl
  src/IceNucleation.jl
  src/parameters/IceNucleation.jl
  test/gpu_tests.jl
  test/homogeneous_ice_nucleation_tests.jl
  test/performance_tests.jl
Labels: Ice :snowman:, Approved :four_leaf_clover:

#371 parcel homogeneous freezing is linear by default
  parcel/ParcelTendencies.jl
Labels: Parcel, Approved :four_leaf_clover:

#374 add JET test_opt to performance tests
  test/Project.toml
  test/performance_tests.jl
Labels: tests, needs review

#376 Fix longruns pipeline
  Project.toml
  ext/EmulatorModelsExt.jl
  test/aerosol_activation_emulators.jl
Labels: tests

#370 Add terminal velocities to P3 scheme
  Project.toml
  docs/Project.toml
  docs/src/API.md
  docs/src/P3Scheme.md
  docs/src/plots/P3SchemePlots.jl
  docs/src/plots/P3TerminalVelocityPlots.jl
  src/Common.jl
  src/P3Scheme.jl
  test/Project.toml
  test/p3_tests.jl
  test/performance_tests.jl
Labels: P3

#378 new r_eff parametrization and update 2-moment formulas radarrefl and …
  docs/bibliography.bib
  docs/src/API.md
  docs/src/Microphysics2M.md
  src/Microphysics2M.jl
  test/microphysics2M_tests.jl
  test/performance_tests.jl
Labels: Approved :four_leaf_clover:

#382 Bump version for a new release
  Project.toml
Labels: packages 🍱

#380 Generalize ice nucleation calibration funcs
  NEWS.md
  papers/ice_nucleation_2024/calibration.jl
  papers/ice_nucleation_2024/calibration_setup.jl
  papers/ice_nucleation_2024/plot_ensemble_mean.jl
  test/ice_nucleation_calibration.jl
  test/performance_tests.jl
Labels: Ice :snowman:, Approved :four_leaf_clover:
