Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2024-12, with the labels that each got.

#487 Prescribed thermo for AIDA calibrations
  docs/Project.toml
  papers/ice_nucleation_2024/AIDA_calibrations.jl
  papers/ice_nucleation_2024/calibration.jl
  papers/ice_nucleation_2024/calibration_setup.jl
  parcel/ParcelCommon.jl
  parcel/ParcelModel.jl
  parcel/Project.toml
  test/Project.toml
  test/performance_tests.jl
Labels: needs review

#493 refactor to prep for AIDA HET calibs
  Artifacts.toml
  papers/Project.toml
  papers/ice_nucleation_2024/AIDA_calibrations.jl
  papers/ice_nucleation_2024/AIDA_data_artifact/OutputArtifacts.toml
  papers/ice_nucleation_2024/AIDA_data_artifact/create_AIDA_artifacts.jl
  papers/ice_nucleation_2024/calibration_setup.jl
  parcel/ParcelCommon.jl
  test/performance_tests.jl
Labels: Approved :four_leaf_clover:

#497 Add ClimaCore GPU test
  .buildkite/pipeline.yml
  test/Project.toml
  test/gpu_clima_core_test.jl
Labels: GPU, ci

#498 update codecov
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
Labels: packages 🍱, ci
