Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2024-03, with the labels that each got.

#339 Switch solver to q/n
  docs/src/P3Scheme.md
  docs/src/plots/P3LambdaErrorPlots.jl
  docs/src/plots/P3ShapeSolverPlots.jl
  src/P3Scheme.jl
  test/p3_tests.jl
Labels: P3, Approved :four_leaf_clover:

#318 Aerosol activation NN
  Project.toml
  ext/Common.jl
  ext/EmulatorModelsExt.jl
  test/Project.toml
  test/emulator_NN.jl
  test/runtests.jl
Labels: enhancement, Aerosol Activation :bulb:, Approved :four_leaf_clover:

#349 Aerosol activation emulators: GP, ET, and ARG-informed
  docs/Project.toml
  docs/src/AerosolActivation.md
  ext/Common.jl
  ext/EmulatorModelsExt.jl
  test/Project.toml
  test/aerosol_activation_emulators.jl
  test/emulator_NN.jl
  test/runtests.jl
Labels: enhancement, Approved :four_leaf_clover:

#333 Add "Flexible Microphysics" option, based on Cloudy.jl
  Project.toml
  docs/make.jl
  docs/src/API.md
  docs/src/MicrophysicsFlexible.md
  ext/CloudyExt.jl
  parcel/Example_NMoment_condensation.jl
  parcel/Project.toml
  src/CloudMicrophysics.jl
  src/MicrophysicsFlexible.jl
  test/Project.toml
  test/microphysicsflexible_tests.jl
Labels: enhancement, Approved :four_leaf_clover:

#350 Added large table calculations for Chen
  docs/src/API.md
  docs/src/plots/Microphysics1M_plots.jl
  docs/src/plots/TerminalVelocityComparisons.jl
  src/Common.jl
  src/Microphysics1M.jl
  src/Microphysics2M.jl
  src/parameters/TerminalVelocity.jl
  test/common_functions_tests.jl
Labels: P3, Approved :four_leaf_clover:

#328 Parcel model with "rainbow" ice nucleation from Frostenberg et al 2023
  docs/src/API.md
  docs/src/IceNucleationParcel0D.md
  docs/src/plots/Frostenberg_fig1.jl
  parcel/Example_Deposition_Nucleation.jl
  parcel/Example_Frostenberg_Immersion_Freezing.jl
  parcel/Example_Immersion_Freezing.jl
  parcel/Example_Jensen_et_al_2022.jl
  parcel/Example_Liquid_only.jl
  parcel/Example_P3_ice_nuc.jl
  parcel/Example_P3_vs_activitybased.jl
  parcel/Example_Tully_et_al_2023.jl
  parcel/ParcelModel.jl
  parcel/ParcelParameters.jl
  parcel/ParcelTendencies.jl
  src/IceNucleation.jl
Labels: enhancement, Ice :snowman:, Parcel, needs review

#355 Cleanup in P3 scheme plots
  docs/src/P3Scheme.md
  docs/src/plots/P3LambdaErrorPlots.jl
  docs/src/plots/P3SchemePlots.jl
Labels: documentation, P3

#357 Delete x_sulph from parcel (not used for now)
  parcel/Example_Deposition_Nucleation.jl
  parcel/Example_Frostenberg_Immersion_Freezing.jl
  parcel/Example_Immersion_Freezing.jl
  parcel/Example_Jensen_et_al_2022.jl
  parcel/Example_Liquid_only.jl
  parcel/Example_P3_ice_nuc.jl
  parcel/Example_P3_vs_activitybased.jl
  parcel/Example_Tully_et_al_2023.jl
  parcel/ParcelModel.jl
  parcel/ParcelTendencies.jl
Labels: Parcel

#360 Adding limiters to DEP and HOM freezing
  parcel/ParcelModel.jl
  parcel/ParcelParameters.jl
  parcel/ParcelTendencies.jl
Labels: Parcel

#361 try using components in codecov
  codecov.yml
Labels: bikeshedding :bike: :house:, ci, needs review

#352 frostenberg docs suggestions
  .gitignore
  docs/Project.toml
  docs/src/IceNucleationParcel0D.md
  parcel/Example_Frostenberg_Immersion_Freezing.jl
  parcel/ParcelModel.jl
  parcel/ParcelTendencies.jl
Labels: documentation, Approved :four_leaf_clover:
