Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2025-03, with the labels that each got.

#524 update CI packages
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
Labels: ci

#522 Use JuliaFormatter.jl
  .JuliaFormatter.toml
  .dev/Project.toml
  .dev/clima_formatter_options.jl
  .dev/climaformat.jl
  .dev/hooks/pre-commit
  .github/workflows/JuliaFormatter.yml
  docs/src/DevelopersGuide.md
Labels: Approved :four_leaf_clover:

#526 Add Asian, MiddleEastern, and Saharan Dust params
  src/parameters/AerosolAsianDust.jl
  src/parameters/AerosolMiddleEasternDust.jl
  src/parameters/AerosolSaharanDust.jl
Labels: parameters :bricks:, Approved :four_leaf_clover:

#516 P3 refactor
  Project.toml
  docs/src/API.md
  docs/src/DevelopersGuide.md
  docs/src/P3Scheme.md
  docs/src/plots/P3AspectRatioPlot.jl
  docs/src/plots/P3GammaAprox.jl
  docs/src/plots/P3LambdaErrorPlots.jl
  docs/src/plots/P3Melting.jl
  docs/src/plots/P3SchemePlots.jl
  docs/src/plots/P3ShapeSolverPlots.jl
  docs/src/plots/P3SlopeParameterizations.jl
  docs/src/plots/P3TerminalVelocityPlots.jl
  docs/src/plots/P3Thresholds.jl
  src/Common.jl
  src/Microphysics1M.jl
  src/P3.jl
  src/P3_helpers.jl
  src/P3_integral_properties.jl
  src/P3_particle_properties.jl
  src/P3_processes.jl
  src/P3_size_distribution.jl
  src/P3_terminal_velocity.jl
  src/parameters/MicrophysicsP3.jl
  test/Project.toml
  test/common_functions_tests.jl
  test/gpu_tests.jl
  test/p3_tests.jl
Labels: P3, Approved :four_leaf_clover:

#533 docs: add P3 multiple solutions example
  docs/src/P3Scheme.md
  docs/src/plots/P3SlopeParameterizations.jl
Labels: P3

#537 calibrate ice nuc params to generic dust
  docs/src/API.md
  papers/ice_nucleation_2024/AIDA_calibrations.jl
  papers/ice_nucleation_2024/calibration.jl
  papers/ice_nucleation_2024/calibration_setup.jl
  papers/ice_nucleation_2024/plots.jl
  papers/ice_nucleation_2024/unpack_AIDA.jl
  src/IceNucleation.jl
  src/parameters/AerosolDust.jl
  src/parameters/Parameters.jl
Labels: needs review
