Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2025-02, with the labels that each got.

#510 Add cloud diagnostics
  docs/make.jl
  docs/src/API.md
  docs/src/CloudDiagnostics.md
  docs/src/Microphysics1M.md
  docs/src/Microphysics2M.md
  src/CloudDiagnostics.jl
  src/CloudMicrophysics.jl
  src/Microphysics1M.jl
  src/Microphysics2M.jl
  src/parameters/Microphysics1M.jl
  test/cloud_diagnostics.jl
  test/microphysics1M_tests.jl
  test/microphysics2M_tests.jl
  test/performance_tests.jl
  test/runtests.jl
Labels: Radiation :sun_with_face:

#511 Bump to v22.7
  Project.toml
Labels: packages 🍱

#512 Add r_eff overwirte based on ClimaParams
  Project.toml
  src/CloudDiagnostics.jl
  test/Project.toml
Labels: packages 🍱

#508 Nonequilibrium in the parcel model
  docs/src/IceNucleationParcel0D.md
  parcel/Example_NonEq.jl
  parcel/ParcelModel.jl
  parcel/ParcelParameters.jl
  parcel/ParcelTendencies.jl
Labels: Approved :four_leaf_clover:

#514 Fix averaging on AIDA
  papers/Project.toml
  papers/ice_nucleation_2024/AIDA_calibrations.jl
  papers/ice_nucleation_2024/calibration.jl
  papers/ice_nucleation_2024/calibration_setup.jl
Labels: Approved :four_leaf_clover:
