Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2025-06, with the labels that each got.

#583 rft: separate mass & number weighted ice terminal velocity
  docs/src/API.md
  docs/src/plots/P3TerminalVelocityPlots.jl
  src/P3_terminal_velocity.jl
  test/p3_tests.jl
Labels: refactor :star2:, Approved :four_leaf_clover:

#585 Update non-equilibrium microphysics API
  Project.toml
  parcel/ParcelTendencies.jl
  src/MicrophysicsNonEq.jl
  test/gpu_tests.jl
  test/microphysics_noneq_tests.jl
  test/performance_tests.jl
Labels: refactor :star2:, Approved :four_leaf_clover:

#588 add number concentration adjustment for 2-moment schemes from Horn 2012
  Project.toml
  docs/bibliography.bib
  docs/src/API.md
  docs/src/Microphysics2M.md
  src/Microphysics2M.jl
  src/parameters/Microphysics2M.jl
  test/Project.toml
  test/gpu_tests.jl
  test/microphysics2M_tests.jl
  test/performance_tests.jl
Labels: needs review, Approved :four_leaf_clover:

#589 Add Julia v1.11 to CI
  .github/workflows/CodeCov.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  docs/src/IceNucleationParcel0D.md
  parcel/Example_NonEq.jl
  parcel/ParcelModel.jl
  parcel/ParcelTendencies.jl
Labels: ci, Approved :four_leaf_clover:

#592 rft: Move `size_distribution` to `DistributionTools`
  docs/src/API.md
  docs/src/plots/P3SlopeParameterizations.jl
  src/DistributionTools.jl
  src/Microphysics2M.jl
  src/P3_integral_properties.jl
  src/P3_processes.jl
  src/P3_size_distribution.jl
  src/P3_terminal_velocity.jl
  test/p3_tests.jl
Labels: Approved :four_leaf_clover:

#581 Remove nonequilibrium phase partition dependency
  src/MicrophysicsNonEq.jl
Labels: Approved :four_leaf_clover:, NonEq 💧🧊

#607 Fix after parameter rename
  Project.toml
  src/parameters/MicrophysicsP3.jl
  test/Project.toml
Labels: bugfix, parameters :bricks:

#590 Sketching a future with different thermo modules
  Project.toml
  docs/src/API.md
  docs/src/plots/ARGplots.jl
  docs/src/plots/ARGplots_fig1.jl
  docs/src/plots/Baumgartner2022_fig5.jl
  docs/src/plots/HomFreezingPlots.jl
  docs/src/plots/KnopfAlpert2013_fig1.jl
  docs/src/plots/KnopfAlpert2013_fig5.jl
  docs/src/plots/MarshallPalmer_distribution.jl
  docs/src/plots/Microphysics1M_plots.jl
  docs/src/plots/Microphysics2M_plots.jl
  docs/src/plots/P3ImmersionFreezing.jl
  docs/src/plots/P3Melting.jl
  docs/src/plots/RainEvapoartionSB2006.jl
  docs/src/plots/T_vs_wateractivity.jl
  docs/src/plots/activity_based_deposition.jl
  ext/Common.jl
  ext/EmulatorModelsExt.jl
  parcel/Example_AerosolActivation.jl
  parcel/Example_Deposition_Nucleation.jl
  parcel/Example_Frostenberg_Immersion_Freezing.jl
  parcel/Example_Immersion_Freezing.jl
  parcel/Example_Jensen_et_al_2022.jl
  parcel/Example_Liquid_only.jl
  parcel/Example_NonEq.jl
  parcel/Example_P3_ice_nuc.jl
  parcel/Example_P3_vs_activitybased.jl
  parcel/Example_Tully_et_al_2023.jl
  parcel/ParcelCommon.jl
  parcel/ParcelModel.jl
  parcel/ParcelParameters.jl
  parcel/ParcelTendencies.jl
  src/AerosolActivation.jl
  src/CloudMicrophysics.jl
  src/Common.jl
  src/DistributionTools.jl
  src/IceNucleation.jl
  src/Microphysics0M.jl
  src/Microphysics1M.jl
  src/Microphysics2M.jl
  src/MicrophysicsNonEq.jl
  src/P3.jl
  src/P3_particle_properties.jl
  src/P3_processes.jl
  src/ThermodynamicsInterface.jl
  test/aerosol_activation_calibration.jl
  test/aerosol_activation_emulators.jl
  test/aerosol_activation_tests.jl
  test/common_functions_tests.jl
  test/gpu_tests.jl
  test/heterogeneous_ice_nucleation_tests.jl
  test/homogeneous_ice_nucleation_tests.jl
  test/microphysics0M_tests.jl
  test/microphysics1M_tests.jl
  test/microphysics2M_tests.jl
  test/microphysics_noneq_tests.jl
  test/p3_tests.jl
  test/performance_tests.jl
  test/ventilation_tests.jl
Labels: refactor :star2:, bikeshedding :bike: :house:

#610 Fix Thermodynamics toml
  Project.toml
Labels: packages 🍱
