Repository CliMA/CloudMicrophysics.jl, pull requests merged in 2025-04, with the labels that each got.

#541 overview plot for calibs
  papers/ice_nucleation_2024/AIDA_calibrations.jl
  papers/ice_nucleation_2024/plots.jl
Labels: Approved :four_leaf_clover:

#545 gpu fixes to Chen2022 term vel
  src/Microphysics1M.jl
  test/gpu_clima_core_test.jl
Labels: Terminal velocity, GPU, needs review

#546 Bump version to 0.22.10
  Project.toml
Labels: packages 🍱

#548 Get rid of FT in noneq cloud formation
  Project.toml
  src/AerosolActivation.jl
  src/CloudDiagnostics.jl
  src/IceNucleation.jl
  src/MicrophysicsNonEq.jl
  src/Nucleation.jl
  test/performance_tests.jl
Labels: ci, Approved :four_leaf_clover:

#549 Add loss plots for AIDA Calibrations
  papers/ice_nucleation_2024/AIDA_calibrations.jl
  papers/ice_nucleation_2024/calibration.jl
  papers/ice_nucleation_2024/plots.jl
Labels: needs review

#551 Compute inverse lambda, safer cloud sources in non-eq.
  docs/src/API.md
  docs/src/plots/MarshallPalmer_distribution.jl
  src/CloudDiagnostics.jl
  src/Common.jl
  src/Microphysics1M.jl
  src/Microphysics2M.jl
  src/MicrophysicsNonEq.jl
  src/parameters/Microphysics1M.jl
Labels: enhancement, Approved :four_leaf_clover:
